import { componentCreator, ComponentCreator, componentFunction } from "./component";

/**
 * A function to return a component creator for an HTML element with the given tag name.
 */
export function htmlComponentCreator<K extends keyof HTMLElementTagNameMap>(
  tagName: K,
): ComponentCreator<HTMLElementTagNameMap[K]> {
  return componentCreator(
    componentFunction(() => document.createElement(tagName)),
  );
}

export const A = htmlComponentCreator('a');
export const Abbr = htmlComponentCreator('abbr');
export const Address = htmlComponentCreator('address');
export const Area = htmlComponentCreator('area');
export const Article = htmlComponentCreator('article');
export const Aside = htmlComponentCreator('aside');
export const Audio = htmlComponentCreator('audio');
export const B = htmlComponentCreator('b');
export const Base = htmlComponentCreator('base');
export const Bdi = htmlComponentCreator('bdi');
export const Bdo = htmlComponentCreator('bdo');
export const Blockquote = htmlComponentCreator('blockquote');
export const Body = htmlComponentCreator('body');
export const Br = htmlComponentCreator('br');
export const Button = htmlComponentCreator('button');
export const Canvas = htmlComponentCreator('canvas');
export const Caption = htmlComponentCreator('caption');
export const Cite = htmlComponentCreator('cite');
export const Code = htmlComponentCreator('code');
export const Col = htmlComponentCreator('col');
export const Colgroup = htmlComponentCreator('colgroup');
export const Data = htmlComponentCreator('data');
export const Datalist = htmlComponentCreator('datalist');
export const Dd = htmlComponentCreator('dd');
export const Del = htmlComponentCreator('del');
export const Details = htmlComponentCreator('details');
export const Dfn = htmlComponentCreator('dfn');
export const Dialog = htmlComponentCreator('dialog');
export const Div = htmlComponentCreator('div');
export const Dl = htmlComponentCreator('dl');
export const Dt = htmlComponentCreator('dt');
export const Em = htmlComponentCreator('em');
export const Embed = htmlComponentCreator('embed');
export const Fieldset = htmlComponentCreator('fieldset');
export const Figcaption = htmlComponentCreator('figcaption');
export const Figure = htmlComponentCreator('figure');
export const Footer = htmlComponentCreator('footer');
export const Form = htmlComponentCreator('form');
export const H1 = htmlComponentCreator('h1');
export const H2 = htmlComponentCreator('h2');
export const H3 = htmlComponentCreator('h3');
export const H4 = htmlComponentCreator('h4');
export const H5 = htmlComponentCreator('h5');
export const H6 = htmlComponentCreator('h6');
export const Head = htmlComponentCreator('head');
export const Header = htmlComponentCreator('header');
export const Hgroup = htmlComponentCreator('hgroup');
export const Hr = htmlComponentCreator('hr');
export const Html = htmlComponentCreator('html');
export const I = htmlComponentCreator('i');
export const Iframe = htmlComponentCreator('iframe');
export const Img = htmlComponentCreator('img');
export const Input = htmlComponentCreator('input');
export const Ins = htmlComponentCreator('ins');
export const Kbd = htmlComponentCreator('kbd');
export const Label = htmlComponentCreator('label');
export const Legend = htmlComponentCreator('legend');
export const Li = htmlComponentCreator('li');
export const Link = htmlComponentCreator('link');
export const Main = htmlComponentCreator('main');
export const Map = htmlComponentCreator('map');
export const Mark = htmlComponentCreator('mark');
export const Menu = htmlComponentCreator('menu');
export const Meta = htmlComponentCreator('meta');
export const Meter = htmlComponentCreator('meter');
export const Nav = htmlComponentCreator('nav');
export const Noscript = htmlComponentCreator('noscript');
export const HtmlObject = htmlComponentCreator('object');
export const Ol = htmlComponentCreator('ol');
export const Optgroup = htmlComponentCreator('optgroup');
export const Option = htmlComponentCreator('option');
export const Output = htmlComponentCreator('output');
export const P = htmlComponentCreator('p');
export const Picture = htmlComponentCreator('picture');
export const Pre = htmlComponentCreator('pre');
export const Progress = htmlComponentCreator('progress');
export const Q = htmlComponentCreator('q');
export const Rp = htmlComponentCreator('rp');
export const Rt = htmlComponentCreator('rt');
export const Ruby = htmlComponentCreator('ruby');
export const S = htmlComponentCreator('s');
export const Samp = htmlComponentCreator('samp');
export const Script = htmlComponentCreator('script');
export const Section = htmlComponentCreator('section');
export const Select = htmlComponentCreator('select');
export const Slot = htmlComponentCreator('slot');
export const Small = htmlComponentCreator('small');
export const Source = htmlComponentCreator('source');
export const Span = htmlComponentCreator('span');
export const Strong = htmlComponentCreator('strong');
export const Style = htmlComponentCreator('style');
export const Sub = htmlComponentCreator('sub');
export const Summary = htmlComponentCreator('summary');
export const Sup = htmlComponentCreator('sup');
export const Table = htmlComponentCreator('table');
export const Tbody = htmlComponentCreator('tbody');
export const Td = htmlComponentCreator('td');
export const Template = htmlComponentCreator('template');
export const Textarea = htmlComponentCreator('textarea');
export const Tfoot = htmlComponentCreator('tfoot');
export const Th = htmlComponentCreator('th');
export const Thead = htmlComponentCreator('thead');
export const Time = htmlComponentCreator('time');
export const Title = htmlComponentCreator('title');
export const Tr = htmlComponentCreator('tr');
export const Track = htmlComponentCreator('track');
export const U = htmlComponentCreator('u');
export const Ul = htmlComponentCreator('ul');
export const Var = htmlComponentCreator('var');
export const Video = htmlComponentCreator('video');
export const Wbr = htmlComponentCreator('wbr');
