import { Observable } from 'rxjs';
export declare const HelloWorld: import("../lib/rxfm").Component<HTMLDivElement>;
export declare const ChildrenExample: import("../lib/rxfm").Component<HTMLDivElement>;
export declare const StylesExample: Observable<HTMLDivElement>;
export declare const DynamicStyles: Observable<HTMLDivElement>;
export declare const ClassExample: Observable<HTMLDivElement>;
export declare const DynamicClasses: Observable<HTMLDivElement>;
export declare const AttributesExample: Observable<HTMLInputElement>;
export declare const DynamicAttributes: Observable<HTMLInputElement>;
export declare const ClickCounter: () => Observable<HTMLButtonElement>;
export declare const ConditionalComponentsExample: import("../lib/rxfm").Component<HTMLDivElement>;
export declare const ComponentArraysExample: () => import("../lib/rxfm").Component<HTMLDivElement>;
